permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: Jinyi Zou
  email: manutdzou@126.com
  link: http://manutdzou.github.io
  github: http://github.com/manutdzou

# 站点信息
title: 邹进屹的博客
description: My personal blog
url: http://manutdzou.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/MS.JPG
favicon: /public/img/we2.jpg

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: http://manutdzou.github.io
  
# disqus 设置
disqus:
  shortname: manutdzou

# 主题设置，自动激活某个标签
active: 科研

# 首页除了最新文章外显示分类
cates: 
  - 深度学习

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档